<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
    $getBlock=$this->getLayout()->createBlock('Magenest\AddToCart\Block\AddToCart');
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $isLogin=$objectManager->create('\Magento\Customer\Model\Session')->isLoggedIn();
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if (($getBlock->isEnable()==true && $isLogin==true) || ($getBlock->isEnable()==false && ($isLogin==true || $isLogin==false))): ?>
    <?php if ($_product->isSaleable()): ?>
        <div class="box-tocart">
            <div class="fieldset">
                <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty" data-bind="scope: 'qty_change'">
                    <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
                    <div class="control">
                        <span class="minus"><button type="button" title="<?= __('Reduce the quantity'); ?>">-</button></span>
                        <input type="number"
                               name="qty"
                               id="qty"
                               value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                               title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                        <span class="plus"><button type="button" title="<?= __('Increase the quantity'); ?>" />+</button></span>
                        <script type="text/javascript">
                            // This is the javascript codes help us to increase and decrease qty
                            require(['jquery'], function($) {
                                $('.box-tocart .minus').on('click', function() {
                                    var qty = parseInt($('#qty').val());
                                    qty = qty - 1;
                                    $('#qty').val(qty).trigger('change');
                                });
                                $('.box-tocart .plus').on('click', function() {
                                    var qty = parseInt($('#qty').val());
                                    qty = qty + 1;
                                    $('#qty').val(qty).trigger('change');
                                });
                                $('#qty').on('change', function() {
                                    var qty = parseInt($(this).val());
                                    if (qty > 100) {
                                        $(this).val('100');
                                    } else if (qty < 1) {
                                        $(this).val('1');
                                    }
                                });
                            });
                        </script>
                    </div>
                </div>
                <?php endif; ?>
                <div class="actions">
                    <button type="submit"
                            title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                            class="action primary to cart newcolor"
                            id="product-addtocart-button">
                        <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
                    </button>
                    <?= $block->getChildHtml('', true) ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
   {
       "#product_addtocart_form": {
           "Magento_Catalog/product/view/validation": {
               "radioCheckboxClosest": ".nested"
           }
       }
   }
</script>
<?php else : ?>
        <script type="text/x-magento-init">
   {
       "#product_addtocart_form": {
           "Magento_Catalog/js/validate-product": {}
       }
   }
</script>
<?php endif; ?>
