<div class="page-actions">
    <div class="page-actions-inner">
        <div class="page-actions-buttons">
            <button
                id="saveMove"
                class="action-primary"
                title="<?php echo __('Save movie') ?>">
                <?php echo __('Save movie') ?>
            </button>
            <button
                id="editMovie"
                class="action-primary"
                title="<?php echo __('Edit movie') ?>">
                <?php echo __('Edit Movie') ?>
            </button>
            <button
                id=deleteMovie"
                class="action-primary"
                title="<?php echo __('Delete movie') ?>">
                <?php echo __('Delete Movie') ?>
            </button>
            <button
                class="action-secondary back"
                title="<?php echo __('Back') ?>">
                <?php echo __('Back') ?>
            </button>
        </div>
    </div>
</div>
