<div class="field phone_number required">
    <label class="label" for="phone_number">
        <span><?= $block->escapeHtml(__('Phone number')) ?></span>
    </label>
    <div class="control">
        <input type="text" name="phone" id="phone" value="" title="<?= $block->escapeHtmlAttr(__('Phone number')) ?>"
               class="input-text" data-validate="{required:true,'phone-validate':true}">
    </div>
</div>
